Revert "WiFi-Hal: Add support to set wifi latency level"
This reverts commit ff394cb1f94454090f4f70c6e294cfb0add83014.

Causes these errors to happen with AOSP tree:
  hardware/qcom/wlan-caf/qcwcn/wifi_hal/wifi_hal.cpp:464:9: error: no member named 'wifi_set_latency_level' in 'wifi_hal_fn'
      fn->wifi_set_latency_level = wifi_set_latency_level;
      ~~  ^
  hardware/qcom/wlan-caf/qcwcn/wifi_hal/wifi_hal.cpp:464:34: error: use of undeclared identifier 'wifi_set_latency_level'
      fn->wifi_set_latency_level = wifi_set_latency_level;
                                   ^
  2 errors generated.

Second one could be easily fixed by adding the missing function header
in common.h. As for the first one, I simply don't want to create a fork
just to add something that's supposed to only be used only with CAF tree
(hence that TARGET_USES_AOSP_FOR_WLAN is exist).

I'd just leave that mess to LineageOS team if they wish.

Signed-off-by: Albert I <krascgq@outlook.co.id>